### ISSUE TITLE
be() method doesn't seem to be working in browser.

### ISSUE THREAD

**Issue by x-yuri** [Modelizer/Selenium#21]
Here's the test:

```php
<?php

use Modelizer\Selenium\SeleniumTestCase;

class SeleniumTest extends SeleniumTestCase
{
    function testBe()
    {
        $this->be(App\User::first());
    }
}
```

And this is what I get:
```
ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'driver'

/srv/http/embo/emboadm/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:292
/srv/http/embo/emboadm/vendor/modelizer/selenium/src/Services/Application.php:94
/srv/http/embo/emboadm/tests/SeleniumTest.php:9
/srv/http/embo/emboadm/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:298
/srv/http/embo/emboadm/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:264
```

**Comment by Modelizer** [comment]
`be` will not work due to it is related to `Illuminate\Foundation\Testing\Concerns\ImpersonatesUsers` and in Selenium you will need to tell it manually.

``` php
$this->visit('login')
     ->submitForm('#login-form', $fields);
```

**Comment by x-yuri** [comment]
Can you explain why it's there? I can't see it used anywhere in the code.

**Comment by jhoopes** [comment]
@x-yuri How are you running this test? 

Are you running it independently from Laravel?  As this package is very tightly coupled with Laravel, running tests like this in isolation don't work.  I had been working on integrating orchestra/testbench into our tests for this package which simulates a Laravel application.  

``` php
$user = User::find(1)
$this->be($user); 
```

should work when running the test with laravel being booted with your test.  This is included with testing because if you want to perform functions within your specific test, like say, during your "setup" part of the test.  PHP Actions will be done as that user.

**however....**  actions performed within the browser **do not** reflect the "be" method.  **the browser is a completely separate session than the one that phpunit is actually running inside of.**

here's a "login" method I have in my test case I use to log into my application as an example...

``` php
protected function login($username, $password)
    {
        // log in as the user within the browser
        $this->visit('/')
            ->type($username, 'username')
            ->type($password, 'password')
            ->press('Login')
            ->see('DASHBOARD')
            ->seePageIs('/home');

        // set the user locally for running php functions as that user
        $user = User::where('username', $username)->first();
        $this->be($user);
        $this->user = $user;

        return $this; // be fluent
    }
```

I add some comments above to help define the 2 separate actions happening there.  This function logs me in both on the browser AND on the PHPUnit side.

An example might be later in my php code, i might want to short circuit some of the browser stuff and say send off an email as my currently logged in user.  Because I'm logged in on the PHPUnit side with "be", I can now do that like...

``` php
function exampleTest()
{
    .
    .

    $this->sendOperationalEmailTo(User::find(5));

    .
    .
    .
}
```

Does that all make sense?  Feel free to ask questions...

**Comment by x-yuri** [comment]
Thanks for your reply. Actually, I think I run it with my `laravel` app. The command is: `./vendor/bin/phpunit`. However, I'm in the process of writing my first tests for it. `./artisan --version` says `5.2.43`. I haven't changed my [`phpunit.xml`](https://github.com/laravel/laravel/blob/v5.2.31/phpunit.xml) yet (couldn't find `5.2.43` tag in that repository).

As for `be()` not being able to affect browser's session, I sort of expected as much. But still I'd like to know, why it fails. Maybe there's something wrong with my app. So, your help would be appreciated. What can I check?

Also, I saw [these](http://stackoverflow.com/a/25009357/52499) [answers](http://stackoverflow.com/questions/15058462/how-to-save-and-load-cookies-using-python-selenium-webdriver/15058521#15058521) on stackoverflow, which suggest to save browser cookies after being authenticated, and then use them as a fixture (pass to the browser every time you need it being authenticated). Is there an easy way to do it in `php`? Or maybe you can consider adding the one in the future.

**Comment by x-yuri** [comment]
Moreover, when I do this in `app/Http/routes.php`:

``` php
Route::get('/t1', function () {
    $this->app['auth']->driver(NULL)->setUser(User::first());
});
```

I get the same error.

**Comment by Modelizer** [comment]
@x-yuri thanks for your suggestion right now there is no cookies shortcut available in this package to authenticate user automatically. It would be nice if you think we can add `be` method which will check cookies and make user authenticated.

Feel free to submit a PR. :+1:

**Comment by x-yuri** [comment]
But before that I should at least know what `be()` is supposed to do, why it triggers the error, and how to use it.

**Comment by Modelizer** [comment]
@x-yuri Frankly speaking I need to dig it more.

@jhoopes I think it would be great if we find a trick to compile this code into smaller one.

``` php
$this->visit('/')
            ->type($username, 'username')
            ->type($password, 'password')
            ->press('Login')
            ->see('DASHBOARD')
            ->seePageIs('/home');

        // set the user locally for running php functions as that user
        $user = User::where('username', $username)->first();
        $this->be($user);
        $this->user = $user;
```

**Comment by Modelizer** [comment]
We need to set the driver https://github.com/Modelizer/Selenium/blob/master/src/Services/Application.php#L92 as referred in https://github.com/laravel/laravel/blob/master/config/auth.php#L69 

@chantezan try
```php
$this->be($user, 'eloquent');
```

**Comment by x-yuri** [comment]
I see now, [your code][m1] might be a bit obsolete (supposedly). Compare it with [this line][l1].

[m1]: https://github.com/Modelizer/Selenium/blob/v1.2.0/src/Services/Application.php#L94
[l1]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Foundation/Testing/Concerns/ImpersonatesUsers.php#L32

So, if you replace `driver` with `guard` in your code, this test will pass:

```php
<?php

namespace Tests;

use Auth;

use Modelizer\Selenium\SeleniumTestCase;

use App\User;

class SeleniumTest extends SeleniumTestCase
{
    function testBe()
    {
        $user = factory(User::class)->create();
        $this->be($user);
        $this->assertEquals($user->id, Auth::user()->id);
    }
}
```

**Comment by Modelizer** [comment]
@x-yuri Thanks for pointing it out, I made changes but still user will not be logged in when a browser is open. The test case will pass but we need to manually authenticate a user in a browser.

**Comment by x-yuri** [comment]
Meaning, `be()` is now working, what's left is to make it work in the browser session? That brings up a couple of questions. Or at least one. How is it supposed to look from user perspective? The most straightforward way is:

```php
function test1() {
    // do login here
    $this->saveCookies();
    ...
}
function test2() {
    $this->restoreCookies();
}
```

But that relies on order of tests. And just doesn't look good to me :) I see it more like some helper methods that simplify creating `login()` (or `beInBrowser()`) method in user's `TestCase` class. Like

```php
class MySeleniumTestCase extends SeleniumTestCase {
    function beInBrowser() {
        if ( ! $this->restoreCookies()) {
            # do login here
            $this->saveCookies();
        }
    }
}
```

Or we can try and provide user with just `beInBrowser` which takes user as a parameter, and forges required cookies, if that is possible.

What do you say?

**Comment by Modelizer** [comment]
I do feel the same. For a faster solution, we usually create a method which will take care of login. But I was thinking to come up with some direct login tricks which will not spend user time on authenticating for every single test. This will consume time when developers have 100s of test to perform. Regarding `beInBrowser` method I'll rather prefer `be` to perform both the actions.

On a side note, Laravel Dusk has this functionality and it will be release soon. As far as I know it is much faster as compared to selenium because it uses phantomJS. Also, Taylor has made some changes in API.
