### ISSUE TITLE
[Enhancement] 0.2 Release and Roadmap.

### ISSUE THREAD

**Issue by Modelizer** [Modelizer/Selenium#6]
@jhoopes I tested it on windows 10 VM its working fine. Please, you take out time and update me on the same. 

Also, I created 0.1 Branch and soon planning to release 0.2 release which will have listed changes below.

In 0.2 release I'm thinking not to add drivers. Rather it will be downloaded as per user required. If a user selected firefox then our script will trigger out which operating system user is running on and download that particular driver for him. This will help us to make this package more lightweight and focus more on API.

Also, @jhoopes any progress on API and database transaction stuff?

**Comment by jhoopes** [comment]
Hi,

Yeah.  I've been working on the API and database transactions and more.  Been a little slow as internet has been flaky for me.

I agree that we probably shouldn't be putting the drivers directly in the repository.

In the branch I'm working on the following features are being worked on: 
- Interacting with the page in an expressive API
- Waiting for elements on a page by CSS Selector, Id, or XPath
- Working with the database (i.e. seeInDatabase, etc)
  - Note that this will not support database transactions, and the reason is, is because you can't enforce database transactions when working with Selenium.  Running tests with selenium by their nature create a completely separate session from the PHPUnit php session running on the CLI.  So even if we added a trait for "DatabaseTransactions" if you make DB changes in your test, like say setting up a test with data, it won't translate across to the brower's session that selenium is running.
- Adding in more expressive exceptions for when errors happen, like "Can't find an element" or "Can't Click Element"
- A few additional enhancements allowing you to "be" a particular user, running artisan commands. 
  
  ---

Additional things after this will be a "framework" for working with JS Widgets.  I currently have 2 of them done, but the way I've implemented them on my local machine isn't really feasible for the long term for adding many more types of widgets.  

After that, I was planning on working on making tests for the library itself so we can test out functionality as we go, unless that's something you want to work on too.

Depending on how internet connections go this weekend, I might have the first set of things done.

**Comment by Modelizer** [comment]
I agree on a lot of things what you said, and also encourage you to keep moving as per your flexibility.

Regarding database transaction which will be handled by Laravel itself. We will use `DB::transaction` to start a transaction and end it as per our needs. If any exception is thrown then Laravel automatically rollback it. Also, we will think about transaction once these things are sorted which we have planned.

Thanks.
